model:
  name: ""
  params:
    dist_measure: "mix"
    lr: 0.05     # 当dataset=HAR时为0.05
    batch_size: 32 # 当dataset=HAR时为256
    wd: 0
    ls: 1         #l3 多粒度学习
    l: 0.01       #l4 正则化系数
    beta: 0.4     #0.4 default
    gamma : 0.5   #0.5 default
dataset: "AtrialFibrillation"
algo: "fedcsl"
federated:
  numClient: 20
  numRound: 500
  numEpoch: 5
  dirichlet_alpha: 1

ablation:
  UseJointKD: True
  UseJointCL: True
  UseScaleKD: True
  UseScaleCL: True
  UseProdictor: False
  UseMTLHomo: False     # 方差多任务学习
  UseACF: True
  UseDistribution: False

logPath: "./result/"
description: "acf with select"