model:
  name: ""
  params:
    dist_measure: "cosine"
    lr: 0.05     # 当dataset=HAR时为0.05
    batch_size: 8 # 当dataset=HAR时为256
    wd: 0
    ls: 1         #l3 多粒度学习
    l: 0.01       #l4 正则化系数

dataset: "HAR"

federated:
  numClient: 3
  numRound: 500
  numEpoch: 3 
  dirichlet_alpha: 1

ablation:
  UseJointKD: True
  UseJointCL: True
  UseScaleKD: True
  UseScaleCL: True
  UseProdictor: False
  UseMTLHomo: False     # 方差多任务学习
  UseACF: True
logPath: "./result/"
description: "ADDACF"